# Site settings
title: Ascend
long_title: Ascend
email: ""
#Description will appear in the document head meta (for
#Google search results) and in your feed.xml site description.
description: > # this means to ignore newlines until "baseurl:"
  Autonomus aerial robotics for fun and learning. 
  Ascend is The Norwegian University of Science and Technology's team in 
  the International Aerial Robotics Competition (IARC).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ascendntnu.github.com" # the base hostname & protocol for your site
github_username:  ascendntnu

# Build settings
markdown: kramdown
exclude: [package.json,less,js,node_modules,bower_components,readme.md,blog.sublime-project,blog.sublime-workspace,bower.json,config.json,gulpfile.js,notes.txt]