# Site settings
title: Ascend NTNU
long_title: Ascend
email: "hi@ascendntnu.no"

#Description will appear in the document head meta (for
#Google search results) and in your feed.xml site description.
#Should be <160 characters.
description: > # this means to ignore newlines until "baseurl:"
  Autonomus aerial robotics. Ascend NTNU is The Norwegian University of Science and Technology's team in 
  the International Aerial Robotics Competition (IARC).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.ascendntnu.no" # the base hostname & protocol for your site
github_username:  ascendntnu
twitter_username: ascendntnu
instagram_username: ascendntnu
facebook_page_url: https://www.facebook.com/ascendntnu
linked_in: https://www.linkedin.com/company/ascend-ntnu

# Build settings
markdown: kramdown

exclude: [package.json,less,js,node_modules,bower_components,readme.md,ascend-homepage.sublime-project,blog.sublime-workspace,bower.json,config.json,gulpfile.js,notes.txt]
# Add site map for search engine optimization
gems:
  - jekyll-sitemap

## Custom variables
env: prod
js-manifest: js-manifest
css-manifest: css-manifest

#Used in keywords meta tag
keywords: "Ascend, NTNU, robotics, autonomus, team, IARC, international, aerial, robotics, competition, AI" 
author: "Ascend NTNU"
